# Generated by Django 4.1 on 2022-08-09 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=10)),
                ('date_of_joining', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.PositiveIntegerField(unique=True)),
                ('no_of_bed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg.room')),
            ],
        ),
    ]
