# Generated by Django 4.1 on 2022-08-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0003_paymentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tv_available',
            field=models.BooleanField(default=True),
        ),
    ]
